http {
    upstream backend {
        server 127.0.0.1:8081;
        server 127.0.0.1:8082;

        # we can choose what load balancing method we want to choose
    }

    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
events {
    worker_connections 1024;
}